void func() {

}

// 17 之前两个func是相同的，但是17之后异常作为类型的一部分会影响重载
// noexcept 和普通版本的函数会被认为是两个不同的类型
void func() noexcept {

}


int main () {


}
